# - nregister: rr
#   - debug: var=rr.resultatame: "Retrieve user password in MYVault"
#   hosts: localhost
#   gather_facts: no
#   tasks:
#   - name: "user information"
#     ansible_module_myvault:
#       myvault_pathname: 'kv_vps/data/[dws] [all] [prd] [fr] [paris] [vmware] [esx] [root] [host]'
#       myvault_user: 'root'

---
- hosts: localhost
  tasks:

  # - name: "get root password from MyVault"
  #   # ansible_module_myvault_root_esxi:
  #   shell: python ansible_module_myvault_root_esxi.py 
  #     # myvault_pathname: 
  #     # myvault_user: 'root'
  #   register: esxi_vault_password
    
  # - debug: var=esxi_vault_password.stdout

    - name: Login into vCenter and get cookies
      uri:
        url: https://vmmsgcid02.fr.world.socgen/rest/com/vmware/cis/session
        force_basic_auth: yes
        validate_certs: no
        method: POST
        user: 'eur\x160462'
        password: 'Dagnu0049'
      register: login
      environment:
        http_proxy:
        https_proxy:
        no_proxy: ".socgen"

    - name: Get All ESXi hostnames
      uri:
        url: "https://vmmsgcid02.fr.world.socgen/rest/vcenter/host"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Cookie: "{{login.set_cookie}}"
      register: vchosts
          
    - name: Set the Power Management Policy of host system to high-performance
      vmware_host_powermgmt_policy:
        hostname: 'vmmsgcid02.fr.world.socgen'
        username: 'eur\x160462'
        password: 'Dagnu0049'
        esxi_hostname:  "{{item.name}}"
        policy: high-performance
        validate_certs: no
      delegate_to: localhost
      with_items: "{{vchosts.json.value}}"