---
- hosts: localhost
  user: root
  tasks:
    # - name: Post playbook id
    #   uri:
    #     url: http://192.175.138.223/esxi_deployator_2000/main_deploy_esxi_4.php
    #     method: GET
    #     return_content: yes
    #     register: thecsv
    # - debug: var=thecsv

  - name: "Identify SESSION"
    shell: "sudo ls -td -- uploads/* | head -n 1 | cut -d'/' -f2"
    register: session
  - debug: var=session

  - name: Log ARA Key
    ara_record:
      # playbook_id: 11
      key: esxi_deploy
      value: 133
    register: version

  - name: "Write pbid in file"
    copy:
      dest: "uploads/{{session.stdout}}/id.txt"
      # dest: "pbid/id.txt"
      content: |
        {{ version.playbook_id }}

  - name: "Identify csv information"
    shell: "sudo ls uploads/{{session.stdout}}/*.csv | cut -d'/' -f3"
    register: thecsv
    become: yes
    args:
      chdir: /usr/share/nginx/html/isos/esxi_deployator_2000
  - debug: var=thecsv
  
  - name: "Reading CSV"
    read_csv:
        path: uploads/{{session.stdout}}/{{ thecsv.stdout }}
        key: Hostname
    register: esxi